config/routes.rb
Rails.application.routes.draw do
  resources :animals
  root  'animals#lander'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	validates :facts, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end
  
  def lander
  end  

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:name, :facts)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	http_basic_authenticate_with name: 'rashmi', password: 'zoovisit1', except: [:index, :show]
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def link_to_image(image_path, target_link,options={})
  link_to(image_tag(image_path, :border => "0"), target_link, options)
end
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class = "placer">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :facts %>
    <%= form.text_area :facts %>
  </div>

  <div class="actions wrapper">
    <%= form.submit "Just Done",:class => "btn btn-info button" %>
  </div>
</div>
<% end %>

app/views/animals/edit.html.erb
<h1 class = "app_heading">Edit Observation</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal, :class => "btn btn-info"%> |
<%= link_to 'Back', animals_path, :class => "btn btn-info" %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class = "app_heading">My Zoo Visit</h1>

<table class = "encountered_animals">
  <thead>
    <tr>
      <th>Name</th>
      <th>Facts</th>
      <th>Modify</th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.name %></td>
        <td><%= animal.facts %></td>
        <td><%= link_to(image_tag("show.png", :class => "action_images"),animal) %>
            <%= link_to(image_tag("edit.jpg", :class => "action_images"), edit_animal_path(animal))%>
            <%= link_to(image_tag("delete.jpg", :class => "action_images"), animal, method: :delete, data: { confirm: 'Are you sure?' })  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="wrapper">
<%= link_to 'New Observation', new_animal_path, :class => "btn btn-info button"%>
</div>

app/views/animals/lander.html.erb
<img src="assets/images/Zoo.jpg" alt="Zoo Image">
<p>
<%= link_to 'MyVisit', animals_path, class: 'nav-link' %>
</p>

app/views/animals/new.html.erb
<h1 class = "app_heading">New Observation</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path, :class => "btn btn-info" %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>
<div class= "placer">
<p>
  <strong>Name:</strong>
  <%= @animal.name %>
</p>

<p>
  <strong>Facts:</strong>
  <%= @animal.facts %>
</p>
</div>
<div class = "wrapper spacer">
<%= link_to 'Edit', edit_animal_path(@animal), :class => "btn btn-info button" %> |
<%= link_to 'Back', animals_path, :class => "btn btn-info button" %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark navbar-static-top navbar-expand-md">
    <div class="container">
        </button> <%= link_to "Everything I Visited!", root_path, class: 'navbar-brand' %>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav mr-auto">
            <li class='nav-item'><%= link_to 'MySafari', animals_path, class: 'nav-link' %></li>

                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= content_for?(:title) ? yield(:title) : "Zoo Visit" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "About Zoo Visit" %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'Index' %>
  </head>

  <body style = "background-color: #4da6ff">
    <header>
      <%#= render 'layouts/navigation' %>
      
    </header>

    <main role="main">
    <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>